name: Build/test
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run build
      - run: npm run test
